
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 31 11:09:40 ART 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int INT = 10;
  public static final int DIVIDE = 6;
  public static final int BOOL = 11;
  public static final int NUMBER = 16;
  public static final int TRUE = 13;
  public static final int SEMI = 2;
  public static final int EQUAL = 9;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int FALSE = 14;
  public static final int ID = 15;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int TIMES = 5;
  public static final int RETURN = 12;
  public static final int LPAREN = 7;
}

