
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jun 18 23:14:59 CST 2017
//----------------------------------------------------

package ejemplo_clase;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int CADENA = 4;
  public static final int INT = 12;
  public static final int COMA = 3;
  public static final int PCOMA = 2;
  public static final int MENOS = 8;
  public static final int POR = 9;
  public static final int ENTERO = 5;
  public static final int STRING = 13;
  public static final int EOF = 0;
  public static final int MAS = 7;
  public static final int TXTCOMILLA = 11;
  public static final int DIV = 10;
  public static final int IGUAL = 6;
  public static final int error = 1;
}

